export default function Head() {
  return (
    <>
      <title>if/else Messenger </title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link
        rel="icon"
        href="https://drive.google.com/uc?export=view&id=1HjKiMFcuCJ_JmU20zZXEVDage1b-e6uT"
      />
    </>
  );
}
